server:
  port: 8040
spring:
  data:
    mongodb:
      username: haifawi
      password: haifawi
      host: localhost
      port: 27017
      database: notification
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notificationGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.micro.notification.kafka.order.OrderConfirmation,paymentConfirmation:com.micro.notification.kafka.payment.PaymentConfirmation
  mail:
    host: localhost
    port: 1025
    username: haifawi
    password: haifawi
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 6000
        timeout: 6000
        writetimeout: 6000
